

Fx_Enrage = {
	[CREATURE_FOOTMAN] = 1,
	[CREATURE_SWORDSMAN] = 1,
	[CREATURE_VINDICATOR] = 1,

	[CREATURE_DEMON] = 1,
	[CREATURE_HORNED_DEMON] = 1,
	[CREATURE_HORNED_LEAPER] = 1,

	[CREATURE_WALKING_DEAD] = 1,
	[CREATURE_ZOMBIE] = 1,
	[CREATURE_DISEASE_ZOMBIE] = 1,

	[CREATURE_TREANT] = 1,
	[CREATURE_TREANT_GUARDIAN] = 1,
	[CREATURE_ANGER_TREANT] = 1,

	[CREATURE_STONE_GARGOYLE] = 1,
	[CREATURE_OBSIDIAN_GARGOYLE] = 1,
	[CREATURE_MARBLE_GARGOYLE] = 1,

	[CREATURE_RIDER] = 1,
	[CREATURE_BEAR_RIDER] = 1,
	[CREATURE_WHITE_BEAR_RIDER] = 1,

	[CREATURE_ORC_WARRIOR] = 1,
	[CREATURE_ORC_SLAYER] = 1,
	[CREATURE_ORC_WARMONGER] = 1,
}
